// 自動生成ファイルの為、手動での編集は上書きされます。
// 生成元シーン : TitleScene

using UnityEngine;

namespace AutoGenerated
{
    /// <summary>TitleScene の合成ルート。</summary>
    public sealed class TitleSceneCompositor : UsefulToolkit.Initialization.GameCompositor<AutoGenerated.TitleSceneCompositor>
    {
        [SerializeField] private ZoukeiJam1.Initialization.Title.TitleInitializer _titleInitializer;

        protected override void InjectAll()
        {
            if (_titleInitializer != null)
            {
                {
                    if (TryGetContent<ZoukeiJam1.Application.SceneTransition.IGameSceneTransition>(out var dep0))
                    {
                        ((UsefulToolkit.Initialization.IInjectable<ZoukeiJam1.Application.SceneTransition.IGameSceneTransition>)_titleInitializer).Inject(dep0);
                    }
                    else
                    {
                        UsefulToolkit.BlackBoard.Logger.UsefulLogger.LogWarning("依存の解決に失敗しました : TitleInitializer (IGameSceneTransition)", this);
                    }
                }
            }

        }

        protected override void InitializeAll(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            if (_titleInitializer != null) _titleInitializer.Initialize(blackBoard);
        }
    }
}
