using AutoGenerated;
using UnityEngine;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Logger;
using UsefulToolkit.BlackBoard.Scene;
using UsefulToolkit.Initialization;
using ZoukeiJam1.Application.SceneTransition;

namespace ZoukeiJam1.Initialization.SceneTransition
{
    /// <summary>
    /// 常駐シーンに置く。GameSceneTransitionService を生成して IGameSceneTransition として DI に登録し、
    /// 遷移の要求先の ISceneState を渡す
    /// </summary>
    public sealed class SceneTransitionInitializer : InitializerBase
    {
        [SerializeField] private BuildScenes _titleScene;
        [SerializeField] private BuildScenes _raceScene;
        [SerializeField] private BuildScenes _resultScene;

        private GameSceneTransitionService _service;

        private void Awake()
        {
            _service = new GameSceneTransitionService((int)_titleScene, (int)_raceScene, (int)_resultScene);
            UsefulToolkitPersistentCompositor.TryRegisterContent<IGameSceneTransition>(_service);
        }

        /// <param name="blackBoard">ISceneState の取得元</param>
        public override void Initialize(IBlackBoard blackBoard)
        {
            if (!blackBoard.GetSceneBoard().TryGetGameState<ISceneState>(out var sceneState))
            {
                UsefulLogger.LogError("ISceneState を取得できなかった為、SceneTransition の初期化を中止しました", this);
                return;
            }

            _service.SetSceneState(sceneState);
            base.Initialize(blackBoard);
        }
    }
}
