// 自動生成ファイルの為、手動での編集は上書きされます。
// 生成元シーン : EngineScene

using UnityEngine;

namespace AutoGenerated
{
    /// <summary>EngineScene の合成ルート。</summary>
    public sealed class EngineSceneCompositor : UsefulToolkit.Initialization.GameCompositor<AutoGenerated.EngineSceneCompositor>
    {
        [SerializeField] private ZoukeiJam1.Initialization.OmikujiEngine.OmikujiEngineInitializer _omikujiEngineInitializer;

        protected override void InjectAll()
        {
            // IInjectableを実装したInitializerはありません。
        }

        protected override void InitializeAll(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            if (_omikujiEngineInitializer != null) _omikujiEngineInitializer.Initialize(blackBoard);
        }
    }
}
