// 自動生成ファイルの為、手動での編集は上書きされます。
// 生成元シーン : EngineScene

using UnityEngine;

namespace AutoGenerated
{
    /// <summary>EngineScene の合成ルート。</summary>
    public sealed class EngineSceneCompositor : UsefulToolkit.Initialization.GameCompositor<AutoGenerated.EngineSceneCompositor>
    {
        [SerializeField] private ZoukeiJam1.Initialization.OmikujiEngine.OmikujiEngineInitializer _omikujiEngineInitializer;
        [SerializeField] private ZoukeiJam1.Initialization.Race.RaceInitializer _raceInitializer;
        [SerializeField] private ZoukeiJam1.Initialization.Motorcycle.MotorcycleInitializer _motorcycleInitializer;

        protected override void InjectAll()
        {
            if (_raceInitializer != null)
            {
                {
                    if (TryGetContent<ZoukeiJam1.BlackBoard.Race.IGameResultRecorder>(out var dep0))
                    {
                        ((UsefulToolkit.Initialization.IInjectable<ZoukeiJam1.BlackBoard.Race.IGameResultRecorder>)_raceInitializer).Inject(dep0);
                    }
                    else
                    {
                        UsefulToolkit.BlackBoard.Logger.UsefulLogger.LogWarning("依存の解決に失敗しました : RaceInitializer (IGameResultRecorder)", this);
                    }
                }
            }

        }

        protected override void InitializeAll(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            if (_omikujiEngineInitializer != null) _omikujiEngineInitializer.Initialize(blackBoard); // order: -10
            if (_raceInitializer != null) _raceInitializer.Initialize(blackBoard);
            if (_motorcycleInitializer != null) _motorcycleInitializer.Initialize(blackBoard); // order: 10
        }
    }
}
