// UsefulToolkit が生成した Initializer のテンプレートです。
// 中身は自由に書き換えられます。再生成時、このファイルが既に存在する場合は上書きされません。
// 生成元シーン : UsefulToolkitPersistent

using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.Initialization;

namespace AutoGenerated
{
    /// <summary>入力システムの初期化と、(map, action) の橋渡しを行う。</summary>
    public sealed class InputInitializer : InputInitializerBase
    {
        private void Awake()
        {
            // 入力の操作面をDIコンテナへ登録する。BlackBoardには載せない。
            // 受け取る側は IInjectable<UsefulToolkit.BlackBoard.Input.IInputController> を実装する。
            UsefulToolkitPersistentCompositor.TryRegisterContent(Controller);
        }

        /// <summary>
        /// 外部入力を仮想デバイスへ書き込む橋渡しを返す。
        /// 外部入力を使う場合は、UsefulToolkit/Input/Generate External Input Device で
        /// 生成した UsefulInputDeviceBridge を返すよう次の行を有効にする。
        /// </summary>
        // protected override UsefulToolkit.BlackBoard.Input.IExternalInputDeviceBridge
        //     CreateExternalInputBridge() => new UsefulInputDeviceBridge();

        /// <param name="blackBoard">InputStateの登録先</param>
        public override void Initialize(IBlackBoard blackBoard)
        {
            base.Initialize(blackBoard);

            // ピストンのドラッグで UI マップの Point / Click を使う
            Controller.SwitchActionMap(ActionMaps.UI);
        }
    }
}
