// 自動生成ファイルの為、手動での編集は上書きされます。
// 生成元シーン : UsefulToolkitPersistent

using UnityEngine;

namespace AutoGenerated
{
    /// <summary>UsefulToolkitPersistent の合成ルート。</summary>
    public sealed class UsefulToolkitPersistentCompositor : UsefulToolkit.Initialization.RootGameCompositor<AutoGenerated.UsefulToolkitPersistentCompositor>
    {
        [SerializeField] private AutoGenerated.InputInitializer _inputInitializer;
        [SerializeField] private ZoukeiJam1.Initialization.Race.GameResultInitializer _gameResultInitializer;
        [SerializeField] private ZoukeiJam1.Initialization.SceneTransition.SceneTransitionInitializer _sceneTransitionInitializer;

        protected override void RegisterChildBoards(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            blackBoard.TryRegisterStateBoard(new UsefulToolkit.BlackBoard.Input.InputBoard());
            blackBoard.TryRegisterStateBoard(new ZoukeiJam1.BlackBoard.OmikujiEngine.OmikujiEngineBoard());
            blackBoard.TryRegisterStateBoard(new ZoukeiJam1.BlackBoard.Race.RaceBoard());
        }

        protected override void InjectAll()
        {
            // IInjectableを実装したInitializerはありません。
        }

        protected override void InitializeAll(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            if (_inputInitializer != null) _inputInitializer.Initialize(blackBoard); // order: -80
            if (_gameResultInitializer != null) _gameResultInitializer.Initialize(blackBoard);
            if (_sceneTransitionInitializer != null) _sceneTransitionInitializer.Initialize(blackBoard);
        }
    }
}
