// 自動生成ファイルの為、手動での編集は上書きされます。
// 生成元シーン : UsefulToolkitPersistent

using UnityEngine;

namespace AutoGenerated
{
    /// <summary>UsefulToolkitPersistent の合成ルート。</summary>
    public sealed class UsefulToolkitPersistentCompositor : UsefulToolkit.Initialization.RootGameCompositor<AutoGenerated.UsefulToolkitPersistentCompositor>
    {
        [SerializeField] private AutoGenerated.InputInitializer _inputInitializer;

        protected override void RegisterChildBoards(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            blackBoard.TryRegisterStateBoard(new UsefulToolkit.BlackBoard.Input.InputBoard());
            blackBoard.TryRegisterStateBoard(new ZoukeiJam1.BlackBoard.OmikujiEngine.OmikujiEngineBoard());
        }

        protected override void InjectAll()
        {
            // IInjectableを実装したInitializerはありません。
        }

        protected override void InitializeAll(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            if (_inputInitializer != null) _inputInitializer.Initialize(blackBoard); // order: -80
        }
    }
}
