// このファイルはUsefulToolkit.Inputによって自動生成されています。直接編集しないでください。
namespace AutoGenerated
{
    public enum PlayerActions
    {
        Move,
        Look,
        Attack,
        Interact,
        Crouch,
        Jump,
        Previous,
        Next,
        Sprint,
    }
}
