// このファイルはUsefulToolkit.Inputによって自動生成されています。直接編集しないでください。
namespace AutoGenerated
{
    public enum UIActions
    {
        Navigate,
        Submit,
        Cancel,
        Point,
        Click,
        RightClick,
        MiddleClick,
        ScrollWheel,
        TrackedDevicePosition,
        TrackedDeviceOrientation,
    }
}
