using System;
using AutoGenerated;
using Unity.Cinemachine;
using UnityEngine;
using UsefulToolkit.BlackBoard.Input;
using UsefulToolkit.Initialization;
using ZoukeiJam1.BlackBoard.OmikujiEngine;

namespace ZoukeiJam1.EngineAdapter.OmikujiEngine
{
    /// <summary>
    /// ピストンのドラッグ入力からクランク角を更新し、クランク・ピストン・コンロッドの Transform に反映する。
    /// 毎フレーム、クランクの動きを <see cref="CrankUpdatedHandler"/> で渡す。
    /// 回転は正転のみ。行程の途中で逆方向へドラッグすると直前に通過した死点まで戻り、そこで止まる
    /// </summary>
    public sealed class OmikujiEngineManager : InitializableMonoBehaviour
    {
        private const float TwoPi = Mathf.PI * 2f;
        private const float DeadCenterHeightTolerance = 1e-4f;
        private const float DeadCenterAngleTolerance = 1e-4f;

        // Enum 型引数へ渡すたびに boxing しないよう、読み取るアクションを保持しておく
        private static readonly Enum UIMap = ActionMaps.UI;
        private static readonly Enum PointAction = UIActions.Point;
        private static readonly Enum ClickAction = UIActions.Click;

        [SerializeField] private Transform _crank;
        [SerializeField] private Transform _crankPin;
        [SerializeField] private Transform _piston;
        [SerializeField] private Transform _arm;
        [SerializeField] private Collider2D _pistonCollider;
        [SerializeField] private Camera _camera;
        [SerializeField] private bool _clockwise = true;

        [Tooltip("死点へ近づく途中で、この距離（エンジンのローカル座標）以内に入ったら死点に到達したとみなす")]
        [SerializeField, Min(0f)] private float _deadCenterSnapDistance = 0.02f;

        [Tooltip("ピストンが上死点に到達したときに発生させる画面振動")]
        [SerializeField] private CinemachineImpulseSource _topDeadCenterImpulse;

        [Tooltip("画面振動の後、ピストンが上死点からこの距離（エンジンのローカル座標）以上離れるまで次の振動を発生させない")]
        [SerializeField, Min(0f)] private float _topDeadCenterImpulseRearmDistance = 0.1f;

        private IInputState _input;
        private OmikujiEngineRig _rig;
        private OmikujiEngineGeometry _geometry;
        private float _initialAngle;

        /// <summary>正転方向に積算したクランク角（rad）</summary>
        private float _angle;

        /// <summary>逆方向へ戻れる下限の角度。直前に通過した死点の角度</summary>
        private float _reverseLimitAngle;

        private bool _isDragging;
        private bool _wasPressed;
        /// <summary>次に上死点へ触れたときに画面振動を発生させてよいか</summary>
        private bool _topDeadCenterImpulseArmed;
        private float _grabOffset;

        private CrankUpdatedHandler _onCrankUpdated;

        /// <summary>現在のピストンの行程</summary>
        public PistonStroke Stroke => StrokeAt(_angle);

        /// <summary>正転方向に積算したクランク角（rad）</summary>
        public float CrankAngle => _angle;

        /// <summary>
        /// シーン上の配置から寸法を読み取り、入力の読み取りを開始する。
        /// 寸法は Crank・CrankPin・Piston がエンジンのローカル座標で初期配置にある前提で求める
        /// </summary>
        /// <param name="input">ドラッグ入力の読み取り元</param>
        public void Initialize(IInputState input)
        {
            _input = input;

            _rig = new OmikujiEngineRig(_crank, _crankPin, _piston, _arm, _clockwise);
            _geometry = _rig.Geometry;
            _initialAngle = _rig.InitialAngle;
            _angle = _initialAngle;
            _reverseLimitAngle = PreviousDeadCenterAngle(_angle);
            _topDeadCenterImpulseArmed = !IsAtTopDeadCenter();

            base.Initialize();
        }

        /// <summary>毎フレームのクランクの動きを渡すコールバックを設定する</summary>
        public void SetCrankUpdatedHandler(CrankUpdatedHandler onCrankUpdated)
        {
            _onCrankUpdated = onCrankUpdated;
        }

        private void Update()
        {
            bool pressed = _input.ReadValue<float>(UIMap, ClickAction).Value > 0.5f;
            Vector2 pointer = ToLocal(_input.ReadValue<Vector2>(UIMap, PointAction).Value);

            if (pressed && !_wasPressed) TryBeginDrag(pointer);
            if (!pressed) _isDragging = false;
            _wasPressed = pressed;

            float previousAngle = _angle;
            if (_isDragging) MovePistonTo(TargetHeightFrom(pointer.y));

            _onCrankUpdated?.Invoke(_angle, _angle - previousAngle, RevolutionCount(), Stroke, Time.deltaTime);
        }

        /// <summary>
        /// ポインタの高さからピストンの目標高さを求める。
        /// 下死点〜上死点を越えた分と死点へ吸い付かせた分は掴んだ位置のずれに吸収し、
        /// 折り返した瞬間からピストンが追従するようにする
        /// </summary>
        private float TargetHeightFrom(float pointerHeight)
        {
            float target = pointerHeight + _grabOffset;
            float adjusted = SnapToDeadCenter(_geometry.ClampHeight(target), _piston.localPosition.y);
            _grabOffset += adjusted - target;
            return adjusted;
        }

        /// <summary>
        /// 現在の行程で向かっている死点へ近づく向きに動いていて、その死点から _deadCenterSnapDistance 以内に入った高さを死点の高さに揃える。
        /// 離れる向きや、直前に通過した死点へは揃えない。揃えると死点へ吸い戻され、逆回転としてミスになる。
        /// 動いた向きは DeadCenterHeightTolerance 以下の差を無視して判定する。ピストンの高さはクランク角から求め直した値で誤差を含むため
        /// </summary>
        private float SnapToDeadCenter(float height, float currentHeight)
        {
            bool movingUp = height - currentHeight > DeadCenterHeightTolerance;
            bool movingDown = currentHeight - height > DeadCenterHeightTolerance;
            PistonStroke stroke = Stroke;

            if (stroke == PistonStroke.Up && movingUp &&
                _geometry.TopDeadCenterHeight - height <= _deadCenterSnapDistance)
                return _geometry.TopDeadCenterHeight;
            if (stroke == PistonStroke.Down && movingDown &&
                height - _geometry.BottomDeadCenterHeight <= _deadCenterSnapDistance)
                return _geometry.BottomDeadCenterHeight;
            return height;
        }

        /// <summary>スクリーン座標をエンジンのローカル座標に変換する</summary>
        private Vector2 ToLocal(Vector2 screenPosition)
        {
            Vector3 world = _camera.ScreenToWorldPoint(screenPosition);
            return transform.InverseTransformPoint(world);
        }

        /// <summary>押した位置がピストン上ならドラッグを開始する</summary>
        private void TryBeginDrag(Vector2 pointerLocal)
        {
            if (!_pistonCollider.OverlapPoint(transform.TransformPoint(pointerLocal))) return;

            _isDragging = true;
            _grabOffset = _piston.localPosition.y - pointerLocal.y;
        }

        /// <summary>ピストンを目標の高さへ動かすクランク角を選び、各部品へ反映する</summary>
        private void MovePistonTo(float targetHeight)
        {
            var (first, second) = _geometry.SolveAngles(targetHeight);
            float firstDelta = WrapPi(first - _angle);
            float secondDelta = WrapPi(second - _angle);

            // 死点からは必ず正転側へ進む。それ以外は現在角に近い方の解を選び、連続的に動かす
            float delta = IsAtDeadCenter()
                ? Mathf.Max(firstDelta, secondDelta)
                : Mathf.Abs(firstDelta) <= Mathf.Abs(secondDelta) ? firstDelta : secondDelta;

            _angle = Mathf.Max(_angle + delta, _reverseLimitAngle);
            _reverseLimitAngle = Mathf.Max(_reverseLimitAngle, PreviousDeadCenterAngle(_angle));

            _rig.ApplyPose(_angle);
            NotifyTopDeadCenterArrival();
        }

        /// <summary>初期状態から正転で上死点を通過した回数</summary>
        private int RevolutionCount()
        {
            return TopDeadCenterPassCount(_angle) - TopDeadCenterPassCount(_initialAngle);
        }

        /// <summary>
        /// 基準の上死点から指定角までに通過した上死点の数。
        /// 逆回転は直前の死点で止まるため、この値が減ることはない
        /// </summary>
        private int TopDeadCenterPassCount(float angle)
        {
            // 上死点ちょうどの角度が浮動小数の誤差で通過前と判定されないよう、わずかに進めて求める
            float probe = angle + DeadCenterAngleTolerance;
            return Mathf.FloorToInt((probe - _geometry.TopDeadCenterAngle) / TwoPi);
        }

        /// <summary>指定角でのピストンの行程。直前に通過した死点が上死点なら Down、下死点なら Up</summary>
        private PistonStroke StrokeAt(float angle)
        {
            float probe = angle + DeadCenterAngleTolerance;
            float sinceTop = Mathf.Repeat(probe - _geometry.TopDeadCenterAngle, TwoPi);
            float sinceBottom = Mathf.Repeat(probe - _geometry.BottomDeadCenterAngle, TwoPi);
            return sinceTop < sinceBottom ? PistonStroke.Down : PistonStroke.Up;
        }

        /// <summary>
        /// 上死点に触れた瞬間に 1 度だけ画面振動を発生させる。
        /// 上死点付近での細かな上下や死点への吸い付きで繰り返し振動しないよう、
        /// 上死点から _topDeadCenterImpulseRearmDistance 以上離れるまで次の振動を発生させない
        /// </summary>
        private void NotifyTopDeadCenterArrival()
        {
            if (_topDeadCenterImpulseArmed && IsAtTopDeadCenter())
            {
                _topDeadCenterImpulseArmed = false;
                if (_topDeadCenterImpulse != null) _topDeadCenterImpulse.GenerateImpulse();
                return;
            }

            float distanceFromTop = _geometry.TopDeadCenterHeight - _geometry.PistonPinAt(_angle).y;
            if (distanceFromTop >= _topDeadCenterImpulseRearmDistance) _topDeadCenterImpulseArmed = true;
        }

        private bool IsAtDeadCenter()
        {
            return IsAtTopDeadCenter() || IsAtBottomDeadCenter();
        }

        private bool IsAtTopDeadCenter()
        {
            return _geometry.PistonPinAt(_angle).y >= _geometry.TopDeadCenterHeight - DeadCenterHeightTolerance;
        }

        private bool IsAtBottomDeadCenter()
        {
            return _geometry.PistonPinAt(_angle).y <= _geometry.BottomDeadCenterHeight + DeadCenterHeightTolerance;
        }

        /// <summary>指定角以下で最も大きい死点の角度（上死点・下死点のどちらか）</summary>
        private float PreviousDeadCenterAngle(float angle)
        {
            // 死点ちょうどの角度が浮動小数の誤差で 1 つ前の死点と判定されないよう、わずかに進めて求める
            float probe = angle + DeadCenterAngleTolerance;
            float top = probe - Mathf.Repeat(probe - _geometry.TopDeadCenterAngle, TwoPi);
            float bottom = probe - Mathf.Repeat(probe - _geometry.BottomDeadCenterAngle, TwoPi);
            return Mathf.Max(top, bottom);
        }

        /// <summary>角度を (-π, π] に収める</summary>
        private static float WrapPi(float angle)
        {
            return Mathf.PI - Mathf.Repeat(Mathf.PI - angle, TwoPi);
        }
    }
}
