using System;
using AutoGenerated;
using UnityEngine;
using UsefulToolkit.BlackBoard.Input;
using UsefulToolkit.Initialization;

namespace ZoukeiJam1.EngineAdapter.OmikujiEngine
{
    /// <summary>
    /// ピストンのドラッグ入力からクランク角を更新し、クランク・ピストン・コンロッドの Transform に反映する。
    /// 回転は正転のみ。行程の途中で逆方向へドラッグすると直前に通過した死点まで戻り、そこで止まる
    /// </summary>
    public sealed class OmikujiEngineManager : InitializableMonoBehaviour
    {
        private const float TwoPi = Mathf.PI * 2f;
        private const float DeadCenterHeightTolerance = 1e-4f;
        private const float DeadCenterAngleTolerance = 1e-4f;

        // Enum 型引数へ渡すたびに boxing しないよう、読み取るアクションを保持しておく
        private static readonly Enum UIMap = ActionMaps.UI;
        private static readonly Enum PointAction = UIActions.Point;
        private static readonly Enum ClickAction = UIActions.Click;

        [SerializeField] private Transform _crank;
        [SerializeField] private Transform _crankPin;
        [SerializeField] private Transform _piston;
        [SerializeField] private Transform _arm;
        [SerializeField] private Collider2D _pistonCollider;
        [SerializeField] private Camera _camera;
        [SerializeField] private bool _clockwise = true;

        private IInputState _input;
        private OmikujiEngineGeometry _geometry;
        private float _initialAngle;
        private Vector2 _initialRodDirection;

        /// <summary>正転方向に積算したクランク角（rad）</summary>
        private float _angle;

        /// <summary>逆方向へ戻れる下限の角度。直前に通過した死点の角度</summary>
        private float _reverseLimitAngle;

        private bool _isDragging;
        private bool _wasPressed;
        private float _grabOffset;

        /// <summary>初期状態から正転した回数</summary>
        public int RevolutionCount => Mathf.FloorToInt((_angle - _initialAngle) / TwoPi);

        /// <summary>
        /// シーン上の配置から寸法を読み取り、入力の読み取りを開始する。
        /// 寸法は Crank・CrankPin・Piston がエンジンのローカル座標で初期配置にある前提で求める
        /// </summary>
        public void Initialize(IInputState input)
        {
            _input = input;

            Vector2 crankCenter = _crank.localPosition;
            Vector2 crankPin = crankCenter + (Vector2)(_crank.localRotation * _crankPin.localPosition);
            Vector2 pistonPin = _piston.localPosition;

            _geometry = new OmikujiEngineGeometry(crankCenter, crankPin, pistonPin, _clockwise);
            _initialAngle = _geometry.AngleOf(crankPin);
            _initialRodDirection = crankPin - pistonPin;
            _angle = _initialAngle;
            _reverseLimitAngle = PreviousDeadCenterAngle(_angle);

            base.Initialize();
        }

        private void Update()
        {
            bool pressed = _input.ReadValue<float>(UIMap, ClickAction).Value > 0.5f;
            Vector2 pointer = ToLocal(_input.ReadValue<Vector2>(UIMap, PointAction).Value);

            if (pressed && !_wasPressed) TryBeginDrag(pointer);
            if (!pressed) _isDragging = false;
            _wasPressed = pressed;

            if (_isDragging) MovePistonTo(TargetHeightFrom(pointer.y));
        }

        /// <summary>
        /// ポインタの高さからピストンの目標高さを求める。
        /// 下死点〜上死点を越えた分は掴んだ位置のずれに吸収し、折り返した瞬間からピストンが追従するようにする
        /// </summary>
        private float TargetHeightFrom(float pointerHeight)
        {
            float target = pointerHeight + _grabOffset;
            float clamped = _geometry.ClampHeight(target);
            _grabOffset += clamped - target;
            return clamped;
        }

        /// <summary>スクリーン座標をエンジンのローカル座標に変換する</summary>
        private Vector2 ToLocal(Vector2 screenPosition)
        {
            Vector3 world = _camera.ScreenToWorldPoint(screenPosition);
            return transform.InverseTransformPoint(world);
        }

        /// <summary>押した位置がピストン上ならドラッグを開始する</summary>
        private void TryBeginDrag(Vector2 pointerLocal)
        {
            if (!_pistonCollider.OverlapPoint(transform.TransformPoint(pointerLocal))) return;

            _isDragging = true;
            _grabOffset = _piston.localPosition.y - pointerLocal.y;
        }

        /// <summary>ピストンを目標の高さへ動かすクランク角を選び、各部品へ反映する</summary>
        private void MovePistonTo(float targetHeight)
        {
            var (first, second) = _geometry.SolveAngles(targetHeight);
            float firstDelta = WrapPi(first - _angle);
            float secondDelta = WrapPi(second - _angle);

            // 死点からは必ず正転側へ進む。それ以外は現在角に近い方の解を選び、連続的に動かす
            float delta = IsAtDeadCenter()
                ? Mathf.Max(firstDelta, secondDelta)
                : Mathf.Abs(firstDelta) <= Mathf.Abs(secondDelta) ? firstDelta : secondDelta;

            _angle = Mathf.Max(_angle + delta, _reverseLimitAngle);
            _reverseLimitAngle = Mathf.Max(_reverseLimitAngle, PreviousDeadCenterAngle(_angle));

            ApplyPose();
        }

        private bool IsAtDeadCenter()
        {
            float height = _geometry.PistonPinAt(_angle).y;
            return height >= _geometry.TopDeadCenterHeight - DeadCenterHeightTolerance
                   || height <= _geometry.BottomDeadCenterHeight + DeadCenterHeightTolerance;
        }

        /// <summary>指定角以下で最も大きい死点の角度（上死点・下死点のどちらか）</summary>
        private float PreviousDeadCenterAngle(float angle)
        {
            // 死点ちょうどの角度が浮動小数の誤差で 1 つ前の死点と判定されないよう、わずかに進めて求める
            float probe = angle + DeadCenterAngleTolerance;
            float top = probe - Mathf.Repeat(probe - _geometry.TopDeadCenterAngle, TwoPi);
            float bottom = probe - Mathf.Repeat(probe - _geometry.BottomDeadCenterAngle, TwoPi);
            return Mathf.Max(top, bottom);
        }

        /// <summary>現在のクランク角をクランク・ピストン・コンロッドの Transform に反映する</summary>
        private void ApplyPose()
        {
            Vector2 crankPin = _geometry.CrankPinAt(_angle);
            Vector2 pistonPin = _geometry.PistonPinAt(_angle);

            float crankDegrees = -(_clockwise ? 1f : -1f) * (_angle - _initialAngle) * Mathf.Rad2Deg;
            _crank.localRotation = Quaternion.Euler(0f, 0f, crankDegrees);
            _piston.localPosition = new Vector3(pistonPin.x, pistonPin.y, _piston.localPosition.z);
            _arm.localRotation = Quaternion.Euler(0f, 0f, Vector2.SignedAngle(_initialRodDirection, crankPin - pistonPin));
        }

        /// <summary>角度を (-π, π] に収める</summary>
        private static float WrapPi(float angle)
        {
            return Mathf.PI - Mathf.Repeat(Mathf.PI - angle, TwoPi);
        }
    }
}
