using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Logger;
using UsefulToolkit.Initialization;
using ZoukeiJam1.Application.Race;
using ZoukeiJam1.BlackBoard.Race;

namespace ZoukeiJam1.Initialization.Race
{
    /// <summary>
    /// 常駐シーンに置く。GameResultService を生成して IGameResultRecorder として DI に登録し、
    /// 結果の State を RaceBoard に登録する
    /// </summary>
    public sealed class GameResultInitializer : InitializerBase
    {
        private GameResultService _service;

        private void Awake()
        {
            _service = new GameResultService();
            AutoGenerated.UsefulToolkitPersistentCompositor.TryRegisterContent<IGameResultRecorder>(_service);
        }

        /// <param name="blackBoard">RaceBoard の取得元</param>
        public override void Initialize(IBlackBoard blackBoard)
        {
            if (!blackBoard.TryGetStateBoard<RaceBoard>(out var raceBoard))
            {
                UsefulLogger.LogError("RaceBoard を取得できなかった為、GameResult の初期化を中止しました", this);
                return;
            }

            _service.RegisterState(raceBoard);
            base.Initialize(blackBoard);
        }
    }
}
